spring.application.name=boulangerie-project
server.port=8080

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=false
spring.flyway.baseline-version=1

springdoc.api-docs.enabled=true
springdoc.api-docs.path=/v1/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
# Spring Security JWT
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9095/realms/boulangerie-realm
# Keycloak server
keycloak.server-url=http://localhost:9095
keycloak.realm=boulangerie-realm
# Admin API
keycloak.admin.username=${KEYCLOAK_ADMIN}
keycloak.admin.password=${KEYCLOAK_ADMIN_PASSWORD}
keycloak.admin.client-id=admin-cli
keycloak.admin.client-secret=${KEYCLOAK_CLIENT_SECRET}
# User authentication client
keycloak.client-id=boulangerie-api
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.time-zone=Africa/Dakar
spring.jackson.date-format= dd/MM/yyyy HH:mm:ss
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}
cloudinary.folder=boulangerie