package com.boulangerie.shared.model;

public enum TypeMouvement {
    PAIEMENT,
    PAIEMENT_ABONNEMENT,
    VERSEMENT_LIVREUR,
    PAIEMENT_FOURNISSEUR,
    DEPENSE_PERIODE,
    REPORT_BENEFICE,
    VERSEMENT_ABONNEMENT,
    REMBOURSEMENT_VENTE,
    COMPLEMENT_PAIEMENT_VENTE,
    REVERSEMENT_ABONNEMENT
}