--
-- PostgreSQL database dump
--

\restrict mR1KeMsVIbekrX7jqcUfw4G1QwI2aBc9ikCAHPRylpxQk66wmTUhcuyI8MQ3O4B

-- Dumped from database version 15.14 (Debian 15.14-1.pgdg13+1)
-- Dumped by pg_dump version 16.14 (Debian 16.14-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

-- *not* creating schema, since initdb creates it


--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA public IS '';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: abonnements; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.abonnements (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    created_by character varying(255),
    updated_at timestamp(6) with time zone NOT NULL,
    updated_by character varying(255),
    actif boolean NOT NULL,
    adresse character varying(255),
    date_debut date NOT NULL,
    date_fin date,
    livreur_id bigint NOT NULL,
    nom character varying(100) NOT NULL
);


--
-- Name: abonnements_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.abonnements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.abonnements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: achats; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.achats (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    created_by character varying(255),
    updated_at timestamp(6) with time zone NOT NULL,
    updated_by character varying(255),
    montant_paye numeric(15,2) NOT NULL,
    montant_total numeric(15,2) NOT NULL,
    statut_achat character varying(255) NOT NULL,
    statut_paiement character varying(255) NOT NULL,
    statut_reception character varying(255) NOT NULL,
    fournisseur_id bigint NOT NULL,
    CONSTRAINT achats_statut_achat_check CHECK (((statut_achat)::text = ANY ((ARRAY['ACTIF'::character varying, 'ANNULE'::character varying])::text[]))),
    CONSTRAINT achats_statut_paiement_check CHECK (((statut_paiement)::text = ANY ((ARRAY['NON_PAYE'::character varying, 'PARTIEL'::character varying, 'PAYE'::character varying])::text[]))),
    CONSTRAINT achats_statut_reception_check CHECK (((statut_reception)::text = ANY ((ARRAY['EN_ATTENTE'::character varying, 'PARTIELLE'::character varying, 'COMPLETE'::character varying])::text[])))
);


--
-- Name: achats_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.achats ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.achats_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: caisses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.caisses (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    created_by character varying(255),
    updated_at timestamp(6) with time zone NOT NULL,
    updated_by character varying(255),
    date_fermeture timestamp(6) with time zone,
    date_ouverture timestamp(6) with time zone NOT NULL,
    solde_final numeric(15,2),
    solde_initial numeric(15,2) NOT NULL,
    solde_physique numeric(15,2),
    statut character varying(255) NOT NULL,
    fermee_par bigint,
    ouverte_par bigint NOT NULL,
    motif_ecart character varying(255),
    CONSTRAINT caisses_statut_check CHECK (((statut)::text = ANY ((ARRAY['OUVERTE'::character varying, 'FERMEE'::character varying])::text[])))
);


--
-- Name: caisses_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.caisses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.caisses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: categories_depense; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.categories_depense (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    created_by character varying(255),
    updated_at timestamp(6) with time zone NOT NULL,
    updated_by character varying(255),
    actif boolean NOT NULL,
    libelle character varying(100) NOT NULL
);


--
-- Name: categories_depense_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.categories_depense ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categories_depense_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: categories_produit; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.categories_produit (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    created_by character varying(255),
    updated_at timestamp(6) with time zone NOT NULL,
    updated_by character varying(255),
    actif boolean NOT NULL,
    libelle character varying(100) NOT NULL
);


--
-- Name: categories_produit_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.categories_produit ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categories_produit_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: clients; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.clients (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    created_by character varying(255),
    updated_at timestamp(6) with time zone NOT NULL,
    updated_by character varying(255),
    actif boolean NOT NULL,
    nom character varying(100) NOT NULL,
    prenom character varying(100),
    telephone character varying(20) NOT NULL
);


--
-- Name: clients_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.clients ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.clients_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: commissions_regle; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.commissions_regle (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    created_by character varying(255),
    updated_at timestamp(6) with time zone NOT NULL,
    updated_by character varying(255),
    date_debut date NOT NULL,
    date_fin date,
    livreur_id bigint NOT NULL,
    montant_par_unite numeric(10,2) NOT NULL,
    produit_id bigint NOT NULL
);


--
-- Name: commissions_regle_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.commissions_regle ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.commissions_regle_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: comptes_abonnement; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.comptes_abonnement (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    created_by character varying(255),
    updated_at timestamp(6) with time zone NOT NULL,
    updated_by character varying(255),
    solde_actuel numeric(15,2) NOT NULL,
    abonnement_id bigint NOT NULL
);


--
-- Name: comptes_abonnement_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.comptes_abonnement ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comptes_abonnement_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: comptes_livreur; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.comptes_livreur (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    created_by character varying(255),
    updated_at timestamp(6) with time zone NOT NULL,
    updated_by character varying(255),
    livreur_id bigint NOT NULL,
    solde_actuel numeric(15,2) NOT NULL
);


--
-- Name: comptes_livreur_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.comptes_livreur ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comptes_livreur_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: comptes_livreur_journalier; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.comptes_livreur_journalier (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    created_by character varying(255),
    updated_at timestamp(6) with time zone NOT NULL,
    updated_by character varying(255),
    date date NOT NULL,
    livreur_id bigint NOT NULL,
    reliquat_fin numeric(15,2),
    reliquat_report numeric(15,2) NOT NULL,
    statut character varying(255) NOT NULL,
    total_a_verser numeric(15,2),
    CONSTRAINT comptes_livreur_journalier_statut_check CHECK (((statut)::text = ANY ((ARRAY['BROUILLON'::character varying, 'CLOTURE'::character varying])::text[])))
);


--
-- Name: comptes_livreur_journalier_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.comptes_livreur_journalier ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comptes_livreur_journalier_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: consommations_journalieres; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.consommations_journalieres (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    created_by character varying(255),
    updated_at timestamp(6) with time zone NOT NULL,
    updated_by character varying(255),
    date date NOT NULL,
    quantite numeric(10,2) NOT NULL,
    ligne_id bigint NOT NULL
);


--
-- Name: consommations_journalieres_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.consommations_journalieres ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.consommations_journalieres_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: depenses_periode; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.depenses_periode (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    created_by character varying(255),
    updated_at timestamp(6) with time zone NOT NULL,
    updated_by character varying(255),
    categorie_id bigint NOT NULL,
    mouvement_id bigint NOT NULL,
    periode_id bigint NOT NULL
);


--
-- Name: depenses_periode_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.depenses_periode ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.depenses_periode_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: destinations_production; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.destinations_production (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    created_by character varying(255),
    updated_at timestamp(6) with time zone NOT NULL,
    updated_by character varying(255),
    abonnement_id bigint,
    canal character varying(255) NOT NULL,
    date date NOT NULL,
    livreur_id bigint,
    prix_unitaire numeric(15,2) NOT NULL,
    produit_id bigint NOT NULL,
    quantite numeric(10,2) NOT NULL,
    lot_id bigint NOT NULL,
    quantite_consommee numeric(10,2),
    CONSTRAINT destinations_production_canal_check CHECK (((canal)::text = ANY ((ARRAY['LIVREUR'::character varying, 'BOUTIQUE'::character varying, 'RATION_PERSONNELLE'::character varying, 'AUMONE'::character varying, 'VENTE_FAST_FOOD'::character varying, 'ABONNEMENT'::character varying, 'AUTRES'::character varying])::text[])))
);


--
-- Name: destinations_production_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.destinations_production ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.destinations_production_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: fournisseurs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.fournisseurs (
    id bigint NOT NULL
);


--
-- Name: ingredients; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ingredients (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    created_by character varying(255),
    updated_at timestamp(6) with time zone NOT NULL,
    updated_by character varying(255),
    actif boolean NOT NULL,
    equivalence_stock numeric(10,2) NOT NULL,
    libelle character varying(100) NOT NULL,
    unite character varying(20) NOT NULL,
    CONSTRAINT ingredients_unite_check CHECK (((unite)::text = ANY ((ARRAY['KG'::character varying, 'SAC'::character varying, 'SACHET'::character varying, 'LITRE'::character varying])::text[])))
);


--
-- Name: ingredients_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ingredients ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ingredients_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: lignes_abonnement; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.lignes_abonnement (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    created_by character varying(255),
    updated_at timestamp(6) with time zone NOT NULL,
    updated_by character varying(255),
    prix_unitaire numeric(15,2) NOT NULL,
    reliquat numeric(15,2) NOT NULL,
    abonnement_id bigint NOT NULL,
    client_id bigint NOT NULL
);


--
-- Name: lignes_abonnement_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.lignes_abonnement ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.lignes_abonnement_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: lignes_achat; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.lignes_achat (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    created_by character varying(255),
    updated_at timestamp(6) with time zone NOT NULL,
    updated_by character varying(255),
    motif_retour character varying(255),
    prix_unitaire numeric(15,2) NOT NULL,
    quantite numeric(15,2) NOT NULL,
    quantite_recue numeric(15,2),
    quantite_retournee numeric(15,2),
    achat_id bigint NOT NULL,
    ingredient_id bigint NOT NULL
);


--
-- Name: lignes_achat_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.lignes_achat ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.lignes_achat_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: lignes_compte_livreur; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.lignes_compte_livreur (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    created_by character varying(255),
    updated_at timestamp(6) with time zone NOT NULL,
    updated_by character varying(255),
    depenses_livreur numeric(15,2) NOT NULL,
    destination_id bigint NOT NULL,
    montant_apres_deduction numeric(15,2) NOT NULL,
    montant_commission numeric(15,2) NOT NULL,
    montant_vente numeric(15,2) NOT NULL,
    prix_commission numeric(10,2) NOT NULL,
    prix_unitaire numeric(10,2) NOT NULL,
    qte_abonnement numeric(10,2) NOT NULL,
    qte_livree numeric(10,2) NOT NULL,
    qte_nette numeric(10,2) NOT NULL,
    qte_offerte numeric(10,2) NOT NULL,
    retours numeric(10,2) NOT NULL,
    journalier_id bigint NOT NULL
);


--
-- Name: lignes_compte_livreur_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.lignes_compte_livreur ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.lignes_compte_livreur_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: lignes_vente_boutique; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.lignes_vente_boutique (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    created_by character varying(255),
    updated_at timestamp(6) with time zone NOT NULL,
    updated_by character varying(255),
    prix_unitaire numeric(15,2) NOT NULL,
    produit_id bigint NOT NULL,
    quantite numeric(10,2) NOT NULL,
    type_vente character varying(255) NOT NULL,
    vente_id bigint NOT NULL,
    produit_libelle character varying(150) NOT NULL,
    quantite_retournee numeric(10,2) DEFAULT 0.00 NOT NULL,
    CONSTRAINT lignes_vente_boutique_type_vente_check CHECK (((type_vente)::text = ANY ((ARRAY['NORMALE'::character varying, 'RESTANT'::character varying])::text[])))
);


--
-- Name: lignes_vente_boutique_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.lignes_vente_boutique ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.lignes_vente_boutique_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: livreurs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.livreurs (
    id bigint NOT NULL
);


--
-- Name: lots_production; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.lots_production (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    created_by character varying(255),
    updated_at timestamp(6) with time zone NOT NULL,
    updated_by character varying(255),
    date date NOT NULL,
    produit_id bigint NOT NULL,
    quantite_prevue numeric(10,2) NOT NULL,
    quantite_realisee numeric(10,2),
    recette_id bigint NOT NULL,
    sacs_farine_utilises numeric(10,2) NOT NULL,
    statut character varying(255) NOT NULL,
    CONSTRAINT lots_production_statut_check CHECK (((statut)::text = ANY ((ARRAY['PLANIFIEE'::character varying, 'EN_COURS'::character varying, 'TERMINEE'::character varying])::text[])))
);


--
-- Name: lots_production_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.lots_production ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.lots_production_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mouvements_caisse; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.mouvements_caisse (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    created_by character varying(255),
    updated_at timestamp(6) with time zone NOT NULL,
    updated_by character varying(255),
    libelle character varying(255),
    type_paiement character varying(255) NOT NULL,
    montant numeric(15,2) NOT NULL,
    sens character varying(255) NOT NULL,
    type_mouvement character varying(255) NOT NULL,
    caisse_id bigint NOT NULL,
    CONSTRAINT mouvements_caisse_sens_check CHECK (((sens)::text = ANY ((ARRAY['ENTREE'::character varying, 'SORTIE'::character varying])::text[]))),
    CONSTRAINT mouvements_caisse_type_mouvement_check CHECK (((type_mouvement)::text = ANY ((ARRAY['PAIEMENT'::character varying, 'PAIEMENT_ABONNEMENT'::character varying, 'VERSEMENT_LIVREUR'::character varying, 'PAIEMENT_FOURNISSEUR'::character varying, 'DEPENSE_PERIODE'::character varying, 'REPORT_BENEFICE'::character varying, 'VERSEMENT_ABONNEMENT'::character varying, 'REMBOURSEMENT_VENTE'::character varying, 'COMPLEMENT_PAIEMENT_VENTE'::character varying, 'REVERSEMENT_ABONNEMENT'::character varying])::text[]))),
    CONSTRAINT mouvements_caisse_type_paiement_check CHECK (((type_paiement)::text = ANY ((ARRAY['CASH'::character varying, 'MOBILE_MONEY'::character varying, 'CARTE'::character varying, 'MIXTE'::character varying])::text[])))
);


--
-- Name: mouvements_caisse_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.mouvements_caisse ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mouvements_caisse_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mouvements_stock; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.mouvements_stock (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    created_by character varying(255),
    updated_at timestamp(6) with time zone NOT NULL,
    updated_by character varying(255),
    date timestamp(6) with time zone NOT NULL,
    ligne_achat_id bigint,
    lot_production_id bigint,
    montant numeric(15,2) NOT NULL,
    motif character varying(255),
    quantite numeric(15,3) NOT NULL,
    statut character varying(255),
    type character varying(255) NOT NULL,
    ingredient_id bigint NOT NULL,
    CONSTRAINT mouvements_stock_statut_check CHECK (((statut)::text = ANY ((ARRAY['VALIDE'::character varying, 'EN_ATTENTE'::character varying, 'ANNULE'::character varying])::text[]))),
    CONSTRAINT mouvements_stock_type_check CHECK (((type)::text = ANY ((ARRAY['RECEPTION_ACHAT'::character varying, 'CONSOMMATION_PRODUCTION'::character varying, 'PERTE'::character varying, 'RETOUR_FOURNISSEUR'::character varying, 'AJUSTEMENT'::character varying])::text[])))
);


--
-- Name: mouvements_stock_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.mouvements_stock ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mouvements_stock_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: paiements; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.paiements (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    created_by character varying(255),
    updated_at timestamp(6) with time zone NOT NULL,
    updated_by character varying(255),
    libelle character varying(255),
    type_paiement character varying(255) NOT NULL,
    montant numeric(15,2) NOT NULL,
    vente_id bigint,
    CONSTRAINT paiements_type_paiement_check CHECK (((type_paiement)::text = ANY ((ARRAY['CASH'::character varying, 'MOBILE_MONEY'::character varying, 'CARTE'::character varying, 'MIXTE'::character varying])::text[])))
);


--
-- Name: paiements_abonnement; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.paiements_abonnement (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    created_by character varying(255),
    updated_at timestamp(6) with time zone NOT NULL,
    updated_by character varying(255),
    libelle character varying(255),
    type_paiement character varying(255) NOT NULL,
    montant numeric(15,2) NOT NULL,
    ligne_abonnement_id bigint NOT NULL,
    CONSTRAINT paiements_abonnement_type_paiement_check CHECK (((type_paiement)::text = ANY ((ARRAY['CASH'::character varying, 'MOBILE_MONEY'::character varying, 'CARTE'::character varying, 'MIXTE'::character varying])::text[])))
);


--
-- Name: paiements_abonnement_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.paiements_abonnement ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.paiements_abonnement_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: paiements_fournisseurs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.paiements_fournisseurs (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    created_by character varying(255),
    updated_at timestamp(6) with time zone NOT NULL,
    updated_by character varying(255),
    libelle character varying(255),
    type_paiement character varying(255) NOT NULL,
    montant numeric(15,2) NOT NULL,
    achat_id bigint NOT NULL,
    CONSTRAINT paiements_fournisseurs_type_paiement_check CHECK (((type_paiement)::text = ANY ((ARRAY['CASH'::character varying, 'MOBILE_MONEY'::character varying, 'CARTE'::character varying, 'MIXTE'::character varying])::text[])))
);


--
-- Name: paiements_fournisseurs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.paiements_fournisseurs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.paiements_fournisseurs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: paiements_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.paiements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.paiements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: periodes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.periodes (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    created_by character varying(255),
    updated_at timestamp(6) with time zone NOT NULL,
    updated_by character varying(255),
    benefice_report numeric(15,2),
    date_debut date NOT NULL,
    date_fin date NOT NULL,
    statut character varying(255) NOT NULL,
    CONSTRAINT periodes_statut_check CHECK (((statut)::text = ANY ((ARRAY['OUVERTE'::character varying, 'FERMEE'::character varying, 'CLOTUREE'::character varying])::text[])))
);


--
-- Name: periodes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.periodes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.periodes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: personnes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.personnes (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    created_by character varying(255),
    updated_at timestamp(6) with time zone NOT NULL,
    updated_by character varying(255),
    actif boolean NOT NULL,
    nom character varying(100) NOT NULL,
    prenom character varying(100),
    telephone character varying(20)
);


--
-- Name: personnes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.personnes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.personnes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: produits; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.produits (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    created_by character varying(255),
    updated_at timestamp(6) with time zone NOT NULL,
    updated_by character varying(255),
    actif boolean NOT NULL,
    libelle character varying(100) NOT NULL,
    prix_detail numeric(15,2) NOT NULL,
    prix_gros numeric(15,2),
    prix_livreur numeric(15,2),
    categorie_id bigint NOT NULL,
    type_produit character varying(30),
    image_public_id character varying(255),
    image_url text
);


--
-- Name: produits_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.produits ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.produits_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: recette_ingredients; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.recette_ingredients (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    created_by character varying(255),
    updated_at timestamp(6) with time zone NOT NULL,
    updated_by character varying(255),
    quantite numeric(15,2) NOT NULL,
    ingredient_id bigint NOT NULL,
    recette_id bigint NOT NULL
);


--
-- Name: recette_ingredients_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.recette_ingredients ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recette_ingredients_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: recettes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.recettes (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    created_by character varying(255),
    updated_at timestamp(6) with time zone NOT NULL,
    updated_by character varying(255),
    actif boolean NOT NULL,
    rendement numeric(10,2) NOT NULL,
    temps_cuisson integer,
    temps_preparation integer,
    version integer NOT NULL,
    produit_id bigint NOT NULL
);


--
-- Name: recettes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.recettes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recettes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: resultat_periode; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.resultat_periode (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    created_by character varying(255),
    updated_at timestamp(6) with time zone NOT NULL,
    updated_by character varying(255),
    ca_abonnements numeric(15,2) NOT NULL,
    ca_autres_produits numeric(15,2) NOT NULL,
    ca_vente_restants numeric(15,2) NOT NULL,
    ca_ventes_boutique numeric(15,2) NOT NULL,
    ca_ventes_livreurs numeric(15,2) NOT NULL,
    credits_deduits numeric(15,2) NOT NULL,
    part_boulangerie numeric(15,2) NOT NULL,
    part_gerant numeric(15,2) NOT NULL,
    reliquat_livreurs_deduit numeric(15,2) NOT NULL,
    total_charges numeric(15,2) NOT NULL,
    periode_id bigint NOT NULL
);


--
-- Name: resultat_periode_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.resultat_periode ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.resultat_periode_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: stock_ingredient_snapshots; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.stock_ingredient_snapshots (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    created_by character varying(255),
    updated_at timestamp(6) with time zone NOT NULL,
    updated_by character varying(255),
    periode_id bigint NOT NULL,
    quantite_solde numeric(15,3) NOT NULL,
    valeur_solde numeric(15,2) NOT NULL,
    ingredient_id bigint NOT NULL
);


--
-- Name: stock_ingredient_snapshots_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.stock_ingredient_snapshots ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stock_ingredient_snapshots_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: stock_ingredients; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.stock_ingredients (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    created_by character varying(255),
    updated_at timestamp(6) with time zone NOT NULL,
    updated_by character varying(255),
    quantite numeric(15,2) NOT NULL,
    seuil_alerte numeric(15,2) NOT NULL,
    valeur_totale numeric(15,2) NOT NULL,
    ingredient_id bigint NOT NULL
);


--
-- Name: stock_ingredients_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.stock_ingredients ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stock_ingredients_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: stock_initial; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.stock_initial (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    created_by character varying(255),
    updated_at timestamp(6) with time zone NOT NULL,
    updated_by character varying(255),
    cout_moyen_pondere numeric(15,2),
    periode_id bigint NOT NULL,
    quantite numeric(15,2) NOT NULL,
    valeur numeric(15,2) NOT NULL,
    ingredient_id bigint NOT NULL
);


--
-- Name: stock_initial_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.stock_initial ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stock_initial_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: stock_produit; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.stock_produit (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    created_by character varying(255),
    updated_at timestamp(6) with time zone NOT NULL,
    updated_by character varying(255),
    quantite numeric(15,2) NOT NULL,
    seuil_alerte numeric(15,2) NOT NULL,
    valeur_totale numeric(15,2) NOT NULL,
    produit_id bigint NOT NULL
);


--
-- Name: stock_produit_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.stock_produit ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stock_produit_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: utilisateurs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.utilisateurs (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    created_by character varying(255),
    updated_at timestamp(6) with time zone NOT NULL,
    updated_by character varying(255),
    actif boolean NOT NULL,
    email character varying(255) NOT NULL,
    keycloak_id character varying(100) NOT NULL,
    nom character varying(100) NOT NULL,
    prenom character varying(100),
    role character varying(255) NOT NULL,
    telephone character varying(20),
    CONSTRAINT utilisateurs_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'MANAGER'::character varying, 'CAISSIER'::character varying, 'GESTIONNAIRE_PRODUCTION'::character varying])::text[])))
);


--
-- Name: utilisateurs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.utilisateurs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.utilisateurs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ventes_boutique; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ventes_boutique (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    created_by character varying(255),
    updated_at timestamp(6) with time zone NOT NULL,
    updated_by character varying(255),
    caisse_id bigint NOT NULL,
    date date NOT NULL,
    statut character varying(255) NOT NULL,
    total numeric(15,2) NOT NULL,
    utilisateur_id bigint NOT NULL,
    motif_annulation character varying(255),
    CONSTRAINT ventes_boutique_statut_check CHECK (((statut)::text = ANY ((ARRAY['OUVERTE'::character varying, 'PAYEE'::character varying, 'ANNULEE'::character varying])::text[])))
);


--
-- Name: ventes_boutique_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ventes_boutique ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ventes_boutique_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: versement_livreurs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.versement_livreurs (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    created_by character varying(255),
    updated_at timestamp(6) with time zone NOT NULL,
    updated_by character varying(255),
    libelle character varying(255),
    type_paiement character varying(255) NOT NULL,
    montant numeric(15,2) NOT NULL,
    journalier_id bigint NOT NULL,
    CONSTRAINT versement_livreurs_type_paiement_check CHECK (((type_paiement)::text = ANY ((ARRAY['CASH'::character varying, 'MOBILE_MONEY'::character varying, 'CARTE'::character varying, 'MIXTE'::character varying])::text[])))
);


--
-- Name: versement_livreurs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.versement_livreurs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.versement_livreurs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: versements_abonnement; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.versements_abonnement (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    created_by character varying(255),
    updated_at timestamp(6) with time zone NOT NULL,
    updated_by character varying(255),
    libelle character varying(255),
    type_paiement character varying(255) NOT NULL,
    montant numeric(15,2) NOT NULL,
    compte_abonnement_id bigint NOT NULL,
    CONSTRAINT versements_abonnement_type_paiement_check CHECK (((type_paiement)::text = ANY ((ARRAY['CASH'::character varying, 'MOBILE_MONEY'::character varying, 'CARTE'::character varying, 'MIXTE'::character varying])::text[])))
);


--
-- Name: versements_abonnement_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.versements_abonnement ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.versements_abonnement_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: abonnements abonnements_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.abonnements
    ADD CONSTRAINT abonnements_pkey PRIMARY KEY (id);


--
-- Name: achats achats_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.achats
    ADD CONSTRAINT achats_pkey PRIMARY KEY (id);


--
-- Name: caisses caisses_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.caisses
    ADD CONSTRAINT caisses_pkey PRIMARY KEY (id);


--
-- Name: categories_depense categories_depense_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categories_depense
    ADD CONSTRAINT categories_depense_pkey PRIMARY KEY (id);


--
-- Name: categories_produit categories_produit_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categories_produit
    ADD CONSTRAINT categories_produit_pkey PRIMARY KEY (id);


--
-- Name: clients clients_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clients
    ADD CONSTRAINT clients_pkey PRIMARY KEY (id);


--
-- Name: commissions_regle commissions_regle_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.commissions_regle
    ADD CONSTRAINT commissions_regle_pkey PRIMARY KEY (id);


--
-- Name: comptes_abonnement comptes_abonnement_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comptes_abonnement
    ADD CONSTRAINT comptes_abonnement_pkey PRIMARY KEY (id);


--
-- Name: comptes_livreur_journalier comptes_livreur_journalier_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comptes_livreur_journalier
    ADD CONSTRAINT comptes_livreur_journalier_pkey PRIMARY KEY (id);


--
-- Name: comptes_livreur comptes_livreur_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comptes_livreur
    ADD CONSTRAINT comptes_livreur_pkey PRIMARY KEY (id);


--
-- Name: consommations_journalieres consommations_journalieres_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.consommations_journalieres
    ADD CONSTRAINT consommations_journalieres_pkey PRIMARY KEY (id);


--
-- Name: depenses_periode depenses_periode_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.depenses_periode
    ADD CONSTRAINT depenses_periode_pkey PRIMARY KEY (id);


--
-- Name: destinations_production destinations_production_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.destinations_production
    ADD CONSTRAINT destinations_production_pkey PRIMARY KEY (id);


--
-- Name: fournisseurs fournisseurs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fournisseurs
    ADD CONSTRAINT fournisseurs_pkey PRIMARY KEY (id);


--
-- Name: ingredients ingredients_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ingredients
    ADD CONSTRAINT ingredients_pkey PRIMARY KEY (id);


--
-- Name: lignes_abonnement lignes_abonnement_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lignes_abonnement
    ADD CONSTRAINT lignes_abonnement_pkey PRIMARY KEY (id);


--
-- Name: lignes_achat lignes_achat_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lignes_achat
    ADD CONSTRAINT lignes_achat_pkey PRIMARY KEY (id);


--
-- Name: lignes_compte_livreur lignes_compte_livreur_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lignes_compte_livreur
    ADD CONSTRAINT lignes_compte_livreur_pkey PRIMARY KEY (id);


--
-- Name: lignes_vente_boutique lignes_vente_boutique_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lignes_vente_boutique
    ADD CONSTRAINT lignes_vente_boutique_pkey PRIMARY KEY (id);


--
-- Name: livreurs livreurs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.livreurs
    ADD CONSTRAINT livreurs_pkey PRIMARY KEY (id);


--
-- Name: lots_production lots_production_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lots_production
    ADD CONSTRAINT lots_production_pkey PRIMARY KEY (id);


--
-- Name: mouvements_caisse mouvements_caisse_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mouvements_caisse
    ADD CONSTRAINT mouvements_caisse_pkey PRIMARY KEY (id);


--
-- Name: mouvements_stock mouvements_stock_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mouvements_stock
    ADD CONSTRAINT mouvements_stock_pkey PRIMARY KEY (id);


--
-- Name: paiements_abonnement paiements_abonnement_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.paiements_abonnement
    ADD CONSTRAINT paiements_abonnement_pkey PRIMARY KEY (id);


--
-- Name: paiements_fournisseurs paiements_fournisseurs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.paiements_fournisseurs
    ADD CONSTRAINT paiements_fournisseurs_pkey PRIMARY KEY (id);


--
-- Name: paiements paiements_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.paiements
    ADD CONSTRAINT paiements_pkey PRIMARY KEY (id);


--
-- Name: periodes periodes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.periodes
    ADD CONSTRAINT periodes_pkey PRIMARY KEY (id);


--
-- Name: personnes personnes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personnes
    ADD CONSTRAINT personnes_pkey PRIMARY KEY (id);


--
-- Name: produits produits_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.produits
    ADD CONSTRAINT produits_pkey PRIMARY KEY (id);


--
-- Name: recette_ingredients recette_ingredients_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recette_ingredients
    ADD CONSTRAINT recette_ingredients_pkey PRIMARY KEY (id);


--
-- Name: recettes recettes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recettes
    ADD CONSTRAINT recettes_pkey PRIMARY KEY (id);


--
-- Name: resultat_periode resultat_periode_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resultat_periode
    ADD CONSTRAINT resultat_periode_pkey PRIMARY KEY (id);


--
-- Name: stock_ingredient_snapshots stock_ingredient_snapshots_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stock_ingredient_snapshots
    ADD CONSTRAINT stock_ingredient_snapshots_pkey PRIMARY KEY (id);


--
-- Name: stock_ingredients stock_ingredients_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stock_ingredients
    ADD CONSTRAINT stock_ingredients_pkey PRIMARY KEY (id);


--
-- Name: stock_initial stock_initial_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stock_initial
    ADD CONSTRAINT stock_initial_pkey PRIMARY KEY (id);


--
-- Name: stock_produit stock_produit_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stock_produit
    ADD CONSTRAINT stock_produit_pkey PRIMARY KEY (id);


--
-- Name: stock_ingredients uk1vfbwuj0dwfscibg69l0gn5km; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stock_ingredients
    ADD CONSTRAINT uk1vfbwuj0dwfscibg69l0gn5km UNIQUE (ingredient_id);


--
-- Name: resultat_periode uk4frlvjx8j46d7bae7ap2aas4p; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resultat_periode
    ADD CONSTRAINT uk4frlvjx8j46d7bae7ap2aas4p UNIQUE (periode_id);


--
-- Name: depenses_periode uk4pp1xkkc12nvo1l2xpdaokmp4; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.depenses_periode
    ADD CONSTRAINT uk4pp1xkkc12nvo1l2xpdaokmp4 UNIQUE (mouvement_id);


--
-- Name: paiements uk8m3dj4pxfj5977myo7wikw5n5; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.paiements
    ADD CONSTRAINT uk8m3dj4pxfj5977myo7wikw5n5 UNIQUE (vente_id);


--
-- Name: lignes_abonnement uk_abonnement_client; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lignes_abonnement
    ADD CONSTRAINT uk_abonnement_client UNIQUE (abonnement_id, client_id);


--
-- Name: clients uk_client_telephone; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clients
    ADD CONSTRAINT uk_client_telephone UNIQUE (telephone);


--
-- Name: consommations_journalieres uk_consommation_ligne_date; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.consommations_journalieres
    ADD CONSTRAINT uk_consommation_ligne_date UNIQUE (ligne_id, date);


--
-- Name: utilisateurs uk_utilisateur_email; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.utilisateurs
    ADD CONSTRAINT uk_utilisateur_email UNIQUE (email);


--
-- Name: utilisateurs uk_utilisateur_keycloak; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.utilisateurs
    ADD CONSTRAINT uk_utilisateur_keycloak UNIQUE (keycloak_id);


--
-- Name: recette_ingredients ukci0gwl1dfk9natonvn9ox34qc; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recette_ingredients
    ADD CONSTRAINT ukci0gwl1dfk9natonvn9ox34qc UNIQUE (recette_id, ingredient_id);


--
-- Name: stock_produit ukdud8ps6u6307banstvdv2p7e7; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stock_produit
    ADD CONSTRAINT ukdud8ps6u6307banstvdv2p7e7 UNIQUE (produit_id);


--
-- Name: versement_livreurs uke8qrt126rtqngn8pqh0dvn7l9; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.versement_livreurs
    ADD CONSTRAINT uke8qrt126rtqngn8pqh0dvn7l9 UNIQUE (journalier_id);


--
-- Name: comptes_livreur ukgn4lpty9hgvg5at1t7us82j67; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comptes_livreur
    ADD CONSTRAINT ukgn4lpty9hgvg5at1t7us82j67 UNIQUE (livreur_id);


--
-- Name: comptes_livreur_journalier ukh9m2gdhho0sdbbjajymgpvb90; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comptes_livreur_journalier
    ADD CONSTRAINT ukh9m2gdhho0sdbbjajymgpvb90 UNIQUE (livreur_id, date);


--
-- Name: recettes ukjycyr6tl6rjlsxrnbxntesy9w; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recettes
    ADD CONSTRAINT ukjycyr6tl6rjlsxrnbxntesy9w UNIQUE (produit_id, version);


--
-- Name: lots_production ukkblrtxm6ah2asl4xy2bkqvoaq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lots_production
    ADD CONSTRAINT ukkblrtxm6ah2asl4xy2bkqvoaq UNIQUE (date, produit_id);


--
-- Name: periodes ukkvkjpwgcr46b9qo3ew7s038xb; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.periodes
    ADD CONSTRAINT ukkvkjpwgcr46b9qo3ew7s038xb UNIQUE (date_debut);


--
-- Name: comptes_abonnement uknk8vs8foggwskyvyxi6j8o96s; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comptes_abonnement
    ADD CONSTRAINT uknk8vs8foggwskyvyxi6j8o96s UNIQUE (abonnement_id);


--
-- Name: stock_initial ukq8l926bgap0vdmwk1bw7yded0; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stock_initial
    ADD CONSTRAINT ukq8l926bgap0vdmwk1bw7yded0 UNIQUE (periode_id, ingredient_id);


--
-- Name: utilisateurs utilisateurs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.utilisateurs
    ADD CONSTRAINT utilisateurs_pkey PRIMARY KEY (id);


--
-- Name: ventes_boutique ventes_boutique_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ventes_boutique
    ADD CONSTRAINT ventes_boutique_pkey PRIMARY KEY (id);


--
-- Name: versement_livreurs versement_livreurs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.versement_livreurs
    ADD CONSTRAINT versement_livreurs_pkey PRIMARY KEY (id);


--
-- Name: versements_abonnement versements_abonnement_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.versements_abonnement
    ADD CONSTRAINT versements_abonnement_pkey PRIMARY KEY (id);


--
-- Name: idx_periode_date_debut; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_periode_date_debut ON public.periodes USING btree (date_debut);


--
-- Name: idx_periode_dates_statut; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_periode_dates_statut ON public.periodes USING btree (date_debut, date_fin, statut);


--
-- Name: idx_periode_statut; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_periode_statut ON public.periodes USING btree (statut);


--
-- Name: idx_vente_caisse; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_vente_caisse ON public.ventes_boutique USING btree (caisse_id);


--
-- Name: idx_vente_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_vente_date ON public.ventes_boutique USING btree (date);


--
-- Name: stock_initial fk11f9ceojri9mqg9d5i69alk8w; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stock_initial
    ADD CONSTRAINT fk11f9ceojri9mqg9d5i69alk8w FOREIGN KEY (ingredient_id) REFERENCES public.ingredients(id);


--
-- Name: resultat_periode fk2hlxd3kcxgpc05trh9391xdy9; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resultat_periode
    ADD CONSTRAINT fk2hlxd3kcxgpc05trh9391xdy9 FOREIGN KEY (periode_id) REFERENCES public.periodes(id);


--
-- Name: depenses_periode fk4ijh8nwhvkdncgp98m1g7qscl; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.depenses_periode
    ADD CONSTRAINT fk4ijh8nwhvkdncgp98m1g7qscl FOREIGN KEY (mouvement_id) REFERENCES public.mouvements_caisse(id);


--
-- Name: livreurs fk4t84nlso2hf42j3st4xxhgakw; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.livreurs
    ADD CONSTRAINT fk4t84nlso2hf42j3st4xxhgakw FOREIGN KEY (id) REFERENCES public.personnes(id);


--
-- Name: caisses fk5y913jo1ytbdcpd966fkd06oj; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.caisses
    ADD CONSTRAINT fk5y913jo1ytbdcpd966fkd06oj FOREIGN KEY (ouverte_par) REFERENCES public.utilisateurs(id);


--
-- Name: lignes_compte_livreur fk6af0oem3lg0l2uvcqnn7akin4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lignes_compte_livreur
    ADD CONSTRAINT fk6af0oem3lg0l2uvcqnn7akin4 FOREIGN KEY (journalier_id) REFERENCES public.comptes_livreur_journalier(id);


--
-- Name: paiements_fournisseurs fk6b5ks6krct2mvgmlw6klf91kc; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.paiements_fournisseurs
    ADD CONSTRAINT fk6b5ks6krct2mvgmlw6klf91kc FOREIGN KEY (achat_id) REFERENCES public.achats(id);


--
-- Name: recette_ingredients fk7xjnr7sno03o6vimvlwpr4fv; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recette_ingredients
    ADD CONSTRAINT fk7xjnr7sno03o6vimvlwpr4fv FOREIGN KEY (recette_id) REFERENCES public.recettes(id);


--
-- Name: mouvements_stock fk8e0yigguvb98mb5hgadk6havw; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mouvements_stock
    ADD CONSTRAINT fk8e0yigguvb98mb5hgadk6havw FOREIGN KEY (ingredient_id) REFERENCES public.ingredients(id);


--
-- Name: ventes_boutique fk8euy5kvvrghr89f2dfc7bw58s; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ventes_boutique
    ADD CONSTRAINT fk8euy5kvvrghr89f2dfc7bw58s FOREIGN KEY (utilisateur_id) REFERENCES public.utilisateurs(id);


--
-- Name: depenses_periode fk9hy08k86sy01u2c2lwvgwhy9x; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.depenses_periode
    ADD CONSTRAINT fk9hy08k86sy01u2c2lwvgwhy9x FOREIGN KEY (categorie_id) REFERENCES public.categories_depense(id);


--
-- Name: stock_produit fk9phy8qnxgnrtt0my9x66wtj4t; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stock_produit
    ADD CONSTRAINT fk9phy8qnxgnrtt0my9x66wtj4t FOREIGN KEY (produit_id) REFERENCES public.produits(id);


--
-- Name: caisses fkatiy3rlyut90jtbdfvr0jpofg; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.caisses
    ADD CONSTRAINT fkatiy3rlyut90jtbdfvr0jpofg FOREIGN KEY (fermee_par) REFERENCES public.utilisateurs(id);


--
-- Name: destinations_production fkax1700s9jsgxtmlgqrughbbx2; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.destinations_production
    ADD CONSTRAINT fkax1700s9jsgxtmlgqrughbbx2 FOREIGN KEY (lot_id) REFERENCES public.lots_production(id);


--
-- Name: paiements_abonnement fkb1a34ngnrlwcire03it6mscex; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.paiements_abonnement
    ADD CONSTRAINT fkb1a34ngnrlwcire03it6mscex FOREIGN KEY (ligne_abonnement_id) REFERENCES public.lignes_abonnement(id);


--
-- Name: depenses_periode fkb1em535crm14l8d5npb7a83dv; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.depenses_periode
    ADD CONSTRAINT fkb1em535crm14l8d5npb7a83dv FOREIGN KEY (periode_id) REFERENCES public.periodes(id);


--
-- Name: lignes_vente_boutique fkeg88w6gpnikojwsko7ggu3eeb; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lignes_vente_boutique
    ADD CONSTRAINT fkeg88w6gpnikojwsko7ggu3eeb FOREIGN KEY (vente_id) REFERENCES public.ventes_boutique(id);


--
-- Name: stock_ingredient_snapshots fkeou83twqa35v9xagjyc7a269w; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stock_ingredient_snapshots
    ADD CONSTRAINT fkeou83twqa35v9xagjyc7a269w FOREIGN KEY (ingredient_id) REFERENCES public.ingredients(id);


--
-- Name: consommations_journalieres fkg77q7oe7lhs47qgwtb29icii8; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.consommations_journalieres
    ADD CONSTRAINT fkg77q7oe7lhs47qgwtb29icii8 FOREIGN KEY (ligne_id) REFERENCES public.lignes_abonnement(id);


--
-- Name: lignes_abonnement fkh4rfdekpqugu446ohpaf4al89; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lignes_abonnement
    ADD CONSTRAINT fkh4rfdekpqugu446ohpaf4al89 FOREIGN KEY (client_id) REFERENCES public.clients(id);


--
-- Name: lignes_achat fkifsl1qo9imwgorkl116hg8fng; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lignes_achat
    ADD CONSTRAINT fkifsl1qo9imwgorkl116hg8fng FOREIGN KEY (ingredient_id) REFERENCES public.ingredients(id);


--
-- Name: stock_ingredients fkj24o5y5gixfp18nbp9qaiuqlb; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stock_ingredients
    ADD CONSTRAINT fkj24o5y5gixfp18nbp9qaiuqlb FOREIGN KEY (ingredient_id) REFERENCES public.ingredients(id);


--
-- Name: versements_abonnement fkjbwks92rbbvh1xkflhrqtb3x4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.versements_abonnement
    ADD CONSTRAINT fkjbwks92rbbvh1xkflhrqtb3x4 FOREIGN KEY (compte_abonnement_id) REFERENCES public.comptes_abonnement(id);


--
-- Name: mouvements_caisse fkjkihdsusm1rq17nqjr8o234hi; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mouvements_caisse
    ADD CONSTRAINT fkjkihdsusm1rq17nqjr8o234hi FOREIGN KEY (caisse_id) REFERENCES public.caisses(id);


--
-- Name: achats fkjphgx9cvysvktboojy9ta7tu6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.achats
    ADD CONSTRAINT fkjphgx9cvysvktboojy9ta7tu6 FOREIGN KEY (fournisseur_id) REFERENCES public.fournisseurs(id);


--
-- Name: paiements fknkbnc7pxs5tfwclupysfphcma; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.paiements
    ADD CONSTRAINT fknkbnc7pxs5tfwclupysfphcma FOREIGN KEY (vente_id) REFERENCES public.ventes_boutique(id);


--
-- Name: recettes fkocaa8cp8xk4bco91hso0ofv3o; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recettes
    ADD CONSTRAINT fkocaa8cp8xk4bco91hso0ofv3o FOREIGN KEY (produit_id) REFERENCES public.produits(id);


--
-- Name: fournisseurs fkoct2v0fmvng46b4d8o2vg864g; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fournisseurs
    ADD CONSTRAINT fkoct2v0fmvng46b4d8o2vg864g FOREIGN KEY (id) REFERENCES public.personnes(id);


--
-- Name: recette_ingredients fkorqd4ave6tahcgoik78n60sq0; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recette_ingredients
    ADD CONSTRAINT fkorqd4ave6tahcgoik78n60sq0 FOREIGN KEY (ingredient_id) REFERENCES public.ingredients(id);


--
-- Name: versement_livreurs fkpekqd3plehqg42bd5rhrtukuf; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.versement_livreurs
    ADD CONSTRAINT fkpekqd3plehqg42bd5rhrtukuf FOREIGN KEY (journalier_id) REFERENCES public.comptes_livreur_journalier(id);


--
-- Name: comptes_abonnement fkpu86nyrp5gn3fxpjlktxyd7cn; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comptes_abonnement
    ADD CONSTRAINT fkpu86nyrp5gn3fxpjlktxyd7cn FOREIGN KEY (abonnement_id) REFERENCES public.abonnements(id);


--
-- Name: produits fkqe4oifuygma8l4lq19k67jb5a; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.produits
    ADD CONSTRAINT fkqe4oifuygma8l4lq19k67jb5a FOREIGN KEY (categorie_id) REFERENCES public.categories_produit(id);


--
-- Name: lignes_abonnement fkqlso5428pveix2jroyuivcu4x; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lignes_abonnement
    ADD CONSTRAINT fkqlso5428pveix2jroyuivcu4x FOREIGN KEY (abonnement_id) REFERENCES public.abonnements(id);


--
-- Name: lignes_achat fkrwmlps9nc9jnayy046ua0ur1w; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lignes_achat
    ADD CONSTRAINT fkrwmlps9nc9jnayy046ua0ur1w FOREIGN KEY (achat_id) REFERENCES public.achats(id);


--
-- PostgreSQL database dump complete
--

\unrestrict mR1KeMsVIbekrX7jqcUfw4G1QwI2aBc9ikCAHPRylpxQk66wmTUhcuyI8MQ3O4B

